#!/bin/sh

git checkout -b $1
echo "Checked out."

git push -u origin $1
echo "Pushed."

git commit --allow-empty -m "empty commit"
echo "Empty committed."

git push -u origin $1
echo "Repushed."

hub pull-request -b $2
echo "Done pull request! Enjoy your developer life!"
