#!/bin/sh

git checkout -b $1
echo "Checked out."

git commit --allow-empty -m "empty commit"
echo "Empty committed."

git push --set-upstream origin $1
echo "Pushed."

hub pull-request -b $2
echo "Done pull request! Enjoy your developer life!"
